# Generated by Django 5.0 on 2023-12-20 21:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "MALE"),
                            ("FEMALE", "FEMALE"),
                            ("OTHER", "OTHER"),
                        ],
                        default="OTHER",
                        max_length=255,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("DOCTOR", "DOCTOR"),
                            ("PROFESSOR", "PROFESSOR"),
                            ("PHARMACY_HELPER", "PHARMACY_HELPER"),
                            ("PATIENT", "PATIENT"),
                        ],
                        default="PATIENT",
                        max_length=100,
                        verbose_name="Your user Grade",
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        default="profile_photo.png",
                        upload_to="profiles/",
                        verbose_name="your profile photo",
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        default="Tells us more about you", verbose_name="your biography"
                    ),
                ),
                (
                    "is_employee",
                    models.BooleanField(
                        default=False,
                        help_text="determine if this user an employee",
                        verbose_name="is an employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
